Add jackknifing
esi-neuroscience/syncopy pull request #435
Opened 2023-02-08 14:51 UTC by tensionhead

Changes Summary
----------------
-
-

Reviewer Checklist
------------------
- [ ] Are testing routines present?
- [ ] Do objects in the global package namespace perform proper parsing of their input? 
- [ ] Are all docstrings complete and accurate?
- [ ] Is the CHANGELOG.md up to date?

2023-02-17 10:28 UTC, dfsp-spirit commented
Please add this great new feature to the Changelog.

2023-02-17 14:05 UTC, tensionhead commented
I would wait for the Changelog until some functionality is exposed to the user API?!

2023-02-20 08:17 UTC, dfsp-spirit commented
> 



> I would wait for the Changelog until some functionality is exposed to the user API?!

Okay!

2023-02-20 08:19 UTC, dfsp-spirit requested changes
Thanks a lot, I just left some minor comments on some technical stuff (some unused vars/imports). Otherwise I think this is ready to be merged.

2023-02-20 09:00 UTC, tensionhead commented on syncopy/tests/test_basedata.py
> -
I very much think so yes..

2023-02-20 09:01 UTC, tensionhead commented on syncopy/statistics/jackknifing.py
> +    log_dict = {}
True, probably better to let the future frontend integration handle the log..

2023-02-20 10:16 UTC, dfsp-spirit approved these changes

2023-02-20 10:16 UTC, merged